<?php
/**
 * Copyright (c) 2013 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
?>
<script type="text/javascript">
//<![CDATA[

    var hawkSearchCache = {
        isInit : false,
        buttonId : null,
        init : function() {
            this.url = '<?php echo $this->getGenerateUrl() ?>';
            this.buttonId = '<?php echo $this->getButtonId()?>';
            this.displayId = "hawksearch_display_msg";
            this.isInit = true;
        },
        generateImageCache : function() {
            if (!this.isInit) {
                this.init();
            }
            new Ajax.Request(this.url, {
                onSuccess: function(transport) {
                    var response = transport.responseText.evalJSON();
                    this.displayResults(response);
                }.bind(this)
            });
        },
        displayResults : function(response) {
            var responseEl = $(this.displayId);
            if (responseEl == null) {
                var responseEl = new Element('p', {id : this.displayId}).addClassName('note');
                Element.insert($(this.buttonId) , {after: responseEl});
            }
            if (response.error) {
                return responseEl.innerHTML = response.error;
            }
            $(this.buttonId).disabled = true;
            $(this.buttonId).addClassName("disabled");
            return responseEl.innerHTML = "Datafeed currently locked";
        }
    }

//]]>
</script>