<form id="co-csh2-form" action="">
<fieldset>
    <ul class="form-list">
    <li id="csh2-form">
        <fieldset>
            <ul>
                <li class="wide">
                    <label for="csh2:like" class="required"><em>*</em><?php echo $this->__('Do you like this post?') ?></label>
                    <div class="input-box">
                        <input type='text' name='csh2[like]'  class="required-entry input-text" id="csh2:like" value='<?php echo $this->getQuote()->getCshLike2()?>'/>
                    </div>
                </li>
            </ul>
        </fieldset>
     </li>
    </ul>
    <div class="buttons-set" id="csh2-buttons-container">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="csh2.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="csh2-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var csh2 = new CshMethod2('co-csh2-form','<?php echo $this->getUrl('custom/onepage/saveCsh2') ?>');
    var cshForm2 = new VarienForm('co-csh2-form');
//]]>
</script>
