<?php
/**
 * Copyright (c) 2013 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
?>
<script type="text/javascript">
	//<![CDATA[
	Validation.add('validate-cron-ajax', 'Cron string is not valid', function(v){
		var status = false;
		new Ajax.Request('<?php echo $this->getValidateUrl() ?>', {
			asynchronous: false,
			parameters: {cronString: v},
			onSuccess: function(t) {
				var res = t.responseText.evalJSON();
				status = res.valid;
			},
			onFailure: function(t) {
				alert('Unable to validate cron string, please refresh page and try again.');
				status = false;
			}
		});
		return status;
	});
	//]]>
</script>