<?php
$_product    = $this->getProduct();
$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
?>

<?php if(1): ?>
    <?php
    $_jsonConfig = $this->getJsonConfig();
    $_renderers = $this->getChild('attr_renderers')->getSortedChildren();
    ?>
    <?php if ($_product->isSaleable() && count($_attributes)):?>
        <dl>
            <?php foreach($_attributes as $_attribute): ?>
                <?php
                $_rendered = false;
                foreach ($_renderers as $_rendererName):
                    $_renderer = $this->getChild('attr_renderers')->getChild($_rendererName);
                    if (method_exists($_renderer, 'shouldRender') && $_renderer->shouldRender($_attribute, $_jsonConfig)):
                        $_renderer->setProduct($_product);
                        $_renderer->setAttributeObj($_attribute);
                        echo $_renderer->toHtml();
                        $_rendered = true;
                        break;
                    endif;
                endforeach;

                if (!$_rendered):
                    ?>
                    <dt><label class="required"><em>*</em><?php echo $_attribute->getLabel() ?></label></dt>
                    <dd<?php if ($_attribute->decoratedIsLast){?> class="last"<?php }?>>
                        <div class="input-box">
                            <select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="iwd-qv-attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
                                <option><?php echo $this->__('Choose an Option...') ?></option>
                            </select>
                        </div>
                    </dd>
                <?php endif; ?>
            <?php endforeach; ?>
        </dl>
        <?php echo $this->getChildHtml('after') ?>
    <?php endif;?>
<?php else: ?>
    <?php if ($_product->isSaleable() && count($_attributes)):?>
        <dl>
        <?php foreach($_attributes as $_attribute): ?>
            <dt><label class="required"><em>*</em><?php echo $_attribute->getLabel() ?></label></dt>
            <dd<?php if ($_attribute->decoratedIsLast){?> class="last"<?php }?>>
                <div class="input-box">
                    <select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="iwd-qv-attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
                        <option><?php echo $this->__('Choose an Option...') ?></option>
                      </select>
                  </div>
            </dd>
        <?php endforeach; ?>
        </dl>
    <?php endif;?>
<?php endif;?>

<script type="text/javascript">
    var spConfigQV = new Product.ConfigQV(<?php echo $this->getJsonConfig() ?>);
    //var swatchesConfig = new Product.ConfigurableSwatchesQV(spConfigQV);
</script>