<?php
/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChild('customer.wishlist.item.options')
    ->setItem($item)
    ->getConfiguredOptions();
?>
<div class="cart-cell">
        <?php if ($product->isSaleable()): ?>
            <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" onclick="setLocation('<?php echo $this->getAddToCartUrl($product) ?>')" class="button btn-cart"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
        <?php else: ?>
            <?php if ($product->getIsSalable()): ?>
                <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
            <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <?php foreach($this->getSortedChildren() as $childName):?>
        <?php echo $this->getChildHtml($childName, false);?>
    <?php endforeach;?>
    <?php if ($product->isVisibleInSiteVisibility()): ?>
        <p><a class="link-edit" href="<?php echo $this->getItemConfigureUrl($item) ?>"><?php echo $this->__('Edit') ?></a></p>
    <?php endif ?>
</div>
