<?php
/**
 * @var Mage_Adminhtml_Block_Template $this
 */
?>
<style>
    .bread-logo {
        width: 133px;
        height: 44px;
        display: block;
        background: url('<?php echo $this->getSkinUrl('bread/images/bread-logo.png'); ?>') 0px 0 no-repeat;
    }

    .bread-brand {
        color: #fff;
        background-color: #0c5a7b;
        border: 1px solid #ddd;
        padding: 10px;
        font-size: 125%;
    }
    
    .bread-advanced {
        margin-bottom:15px;
    }

    .form-list .bread-clearer{
        clear: both;
        height: 5px;
    }

    .form-list .bread-send-mail{
        margin-left: 5px;
        cursor: pointer;
    }

    .form-list .bread-send-mail img{
        height: 33px;
    }

    .form-list .bread-create-cart{
        float:left;
    }

    .form-list .bread-create-cart input{
        height: 33px;
    }

    .form-list .bread-title{
        font-size: larger;
    }

    #bread-success-message{
        font-size: 13px;
        font-weight: 600;
    }

    #bread-success-message span {
        color: #eb5e00;
        font-weight: 800;
    }
</style>
