<script type="text/javascript">
//<![CDATA[
OptionTemplateHtml = '<table class="border" cellpadding="0" cellspacing="0">'+
        '<tr class="headings">'+
			'<th class=""><?php echo Mage::helper('formbuilder')->__('HTML') ?> </th>'+
        '</tr>'+
        '<tr>'+
			'<td class=""><textarea name="product[options][{{fieldset}}][{{option_id}}][html]"  class="textarea formbuilder-textarea" rows="7">{{html_content}}</textarea></td>'+
        '</tr>'+
    '</table>';

if ($('option_panel_type_text')) {
    $('option_panel_type_text').remove();
}
//]]>
</script>

<style>
	.formbuilder-textarea { width:500px;}
</style>