<?php
/**
 * @see Enterprise_CustomerBalance_Block_Checkout_Onepage_Payment_Additional
 */
?>
<?php if ($this->isDisplayContainer()): ?>
    <div class="checkout-onepage-payment-additional-customerbalance" id="customerbalance_placer">
        <input type="checkbox" class="checkbox" name="payment[use_customer_balance]" value="<?php echo ($this->isCustomerBalanceUsed() ? '1' : '0') ?>" id="use_customer_balance" <?php echo ($this->isCustomerBalanceUsed() ? 'checked' : '') ?>/>

        <?php $balance = Mage::helper('core')->currency($this->getBalance()); ?>
        <label for="use_customer_balance">
        <strong>
            <?php echo Mage::helper('enterprise_customerbalance')->__('Use Store Credit'); ?>
            (<span id="customerbalance_available_amount"><?php echo $balance; ?></span>
            <?php echo Mage::helper('enterprise_customerbalance')->__('available'); ?>)
        </strong>
        </label>
    </div>
    <script type="text/javascript">
        switchCustomerBalanceCheckboxOSC = function () {
            if ($('use_customer_balance').checked)
                $('use_customer_balance').value = 1;
            else
                $('use_customer_balance').value = 0;
            save_shipping_method(shipping_method_url, 1, 1);
        }
        Event.observe($('use_customer_balance'), 'click', switchCustomerBalanceCheckboxOSC);
    </script>
<?php endif; ?>
