<div id="checkout-review-table-wrapper">
    <table class="data-table" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
        <col width="1" />
        <?php endif; ?>
        <thead>
            <tr>
                <th rowspan="<?php echo $rowspan ?>"><?php echo Mage::helper('checkout')->__('Product Name') ?></th>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo Mage::helper('checkout')->__('Price') ?></th>
                <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo Mage::helper('checkout')->__('Qty') ?></th>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo Mage::helper('checkout')->__('Subtotal') ?></th>
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
        </thead>
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
aitCheckout.createStep('review',{
    deleteGiftUrl :     '<?php echo $this->getUrl('aitcheckout/cart/remove', array('_secure'=>true)) ?>'
}, {
    doCheckErrors : false,
    isLoadWaiting : true,
    isUpdateOnReload : false,
    doNotInitAfter : false,
    container: 'checkout-step-review',
    ids: {
        productOptions:   '.product-options',
        itemQuantity:     '.aititemqty',
        buttonIncrease:   '.btn-increase',
        buttonDecrease:   '.btn-decrease',
        buttonRemove:     '.btn-remove2',
        buttonWishlist:   '.btn-move-to-wishlist',
        buttonRemoveGift: '.btn-remove3',
        buttonAitBalance: '.ait-use-customer-balance',
        buttonAitRewards: '.ait-use-reward-points'
    }
});

//]]>
</script>
