<?php
	$orderId = $this->getInfo()->getOrder()->getId();
	$sageinfo = $this->getSageInfo();
//	var_dump($sageinfo);
	$isReleased = (int)$this->getInfo()->getReleased();
	$isAuthorised = $sageinfo->getAuthorised();
	$isAborted = (int)$this->getInfo()->getAborted();
//	$isVoided = (int)$this->getInfo()->getVoided();
	$isVoided = $sageinfo->getVoided();
	$status = $this->getInfo()->getStatus();
	$CcTransId = $this->getInfo()->getCcTransId();
	$avsIndicator = $this->getInfo()->getCcAvsStatus();
//	$cvvIndicator = $sageinfo->getCvvIndicator();
//	$avsIndicator = $sageinfo->getAvsIndicator();
	$cvvIndicator = $this->getInfo()->getPoNumber();
	$riskIndicator = $sageinfo->getRiskIndicator();

	$adminUsername = Mage::getSingleton('admin/session')->getUser()->getUsername();

	$refunds = $this->getRefundsCollection();
?>
<script type="text/javascript">
	var TOTAL_ORDER_AMOUNT = <?php echo $this->getInfo()->getOrder()->getGrandTotal(); ?>;
	var SUB_TOTAL_ORDER_AMOUNT = <?php echo $this->getInfo()->getOrder()->getSubtotal(); ?>;
</script>

	<ul style="border:1px solid #ccc;margin-bottom:10px;padding:10px;">
		<li><strong><?php echo $this->__('Reference'); ?></strong>: <?php echo $this->getInfo()->getCcTransId(); ?></li>
		<li><strong><?php echo $this->__('Code'); ?></strong>: <?php echo $this->getInfo()->getLastTransId(); ?></li>
		<li><strong><?php echo $this->__('Cvv'); ?></strong>: <?php echo $this->getCvvDescription($cvvIndicator); ?></li>
		<li><strong><?php echo $this->__('Avs'); ?></strong>: <?php echo $this->getAvsDescription($avsIndicator); ?></li>
	</ul>
   <p>

	</p>
	<br />
	<?php if($refunds->getSize()):
		    echo $this->__('<strong>REFUND</strong>s');
	?>
	<div class="grid">
		<table class="data" cellspacing="0">
			<thead>
				<tr class="headings">
					<th><?php echo $this->__('Status'); ?></th>
					<th><?php echo $this->__('Amount'); ?></th>
					<th><?php echo $this->__('Auth No'); ?></th>
					<th><?php echo $this->__('Date'); ?></th>
				</tr>
			</thead>
			<tbody class="even">
				<?php foreach($refunds->getItems() as $rfnd): ?>
				<tr class="border">
					<td><?php echo $rfnd->getStatus(); ?></td>
					<td><?php echo Mage::helper('core')->currency($rfnd->getAmountRefunded()); ?></td>
					<td><?php echo $rfnd->getVpsTxId(); ?></td>
					<td><?php echo $this->formatDate($rfnd->getRefundedOn(), 'short', true); ?></td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<?php endif; ?>

