<?php
/**
 * Copyright (c) 2013 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
 * KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
 * PARTICULAR PURPOSE.
 */
?>
<script type="text/javascript">
	//<![CDATA[

	var hawkSearchProxy = {
		isInit : false,
		buttonId : null,
		init : function() {
			this.url = '<?php echo $this->getSynchronizeUrl() ?>';
			this.buttonId = '<?php echo $this->getButtonId()?>';
			this.forceId = 'syncforce';
			this.displayId = "hawksearch_display_msg";
			this.isInit = true;
		},
		syncCategories : function() {
			if (!this.isInit) {
				this.init();
			}
			var isForce = false;
			if($(this.forceId)){
				isForce = $(this.forceId).checked;
			}
			new Ajax.Request(this.url, {
				parameters: {force: isForce},
				onSuccess: function(transport) {
					var response = transport.responseText.evalJSON();
					this.displayResults(response);
				}.bind(this)
			});
		},
		displayResults : function(response) {
			var responseEl = $(this.displayId);
			if (responseEl == null) {
				var responseEl = new Element('p', {id : this.displayId}).addClassName('note');
				Element.insert($(this.buttonId) , {after: responseEl});
			}
			if (response.error) {
				return responseEl.innerHTML = response.error;
			}
			$(this.buttonId).disabled = true;
			$(this.buttonId).addClassName("disabled");
			if($(this.forceId) != null) {
				$(this.forceId).disabled = true;
			}
			return responseEl.innerHTML = "<?php echo Mage::helper('hawksearch_proxy/data')->getAjaxNotice(false); ?>";
		},
		forceSync: function() {
			if (!this.isInit) {
				this.init();
			}
			if($(this.forceId).checked && $(this.buttonId).disabled){
				$(this.buttonId).disabled = false;
				$(this.buttonId).removeClassName("disabled");
			} else {
				$(this.buttonId).disabled = true;
				$(this.buttonId).addClassName("disabled");
			}
		}
	}

	//]]>
</script>