<?php $message =  $this->getMessagesBlock()->toHtml() ?>
<?php //if (strlen($message)>10):
?>
<!--<div id="messages_product_view">--><?php //echo $message?><!--</div>-->
<?php //else:?>
<?php
	$product = $this->getData('product');
	$update = $this->getData('updateProduct');
	if (!$update){
		$message = Mage::helper('checkout')->__('%s was added to your shopping cart.', Mage::helper('core')->htmlEscape($product->getName()));
	}else{
		$message = Mage::helper('checkout')->__('Item was updated in your shopping cart.');
	}
?>
<div class="iwd-qv-messages" style="display:block">
<!--    <i class="fa fa-2x fa-exclamation-circle"></i>-->
    <p class="iwd-qv-message-success"><?php echo $message?></p>
</div>
<?php //endif;?>
<div class="es-action">
	<a class="iwd-qv-button es-btn-checkout" href="<?php echo Mage::helper('checkout/url')->getCheckoutUrl()?>"><?php echo $this->__('Checkout')?></a>
	<a class="iwd-qv-button right close-ajax-dialog" data-dismiss="modal"><?php echo $this->__('Continue Shopping')?></a>
</div>
<script>
    <?php
    // make popup fixed - when product has long desc., confirmation popup is located in the top, and user can't see it - so we'll make it pos. fixed
    ?>
    jQueryIWD('.iwd-qv-modal-dialog').addClass('iwd-success-cart');
</script>