<?php
/**
 * @see Enterprise_GiftCardAccount_Block_Checkout_Cart_Giftcardaccount
 */
?>

<div id="co-giftcard-form">
    <fieldset>
        <div style="display:none;" id="giftcard-notice" class="error-msg"></div>
        <div id="giftcard_balance_lookup"></div>
        <span id="gc-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo Mage::helper('core')->__('Please wait, loading...') ?>
        </span>
        <ul class="form-list">

            <li>
                <label for="giftcard_code"><?php echo $this->__('Enter the gift card code') ?></label>
                <div class="input-box">
                    <input class="input-text" id="giftcard_code" name="giftcard_code" value="" />
                </div>
            </li>
            <li>
                <button id="giftcard-apply-button" class="button" type="button" value="<?php echo $this->__('Add Gift Card') ?>"><span><span><?php echo $this->__('Add Gift Card') ?></span></span></button>
            </li>
                <button class="button check-gc-status" onclick="new Ajax.Updater('giftcard_balance_lookup', '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck') ?>', {onCreate: function() { $('gc-please-wait').show() }, onComplete: function() { $('gc-please-wait').hide() }, parameters : {giftcard_code : $('giftcard_code').value}})" type="button" value="<?php echo $this->__('Check Gift Card status and balance') ?>"><span><span><?php echo $this->__('Check Gift Card status and balance') ?></span></span></button>
            
        </ul>
    </fieldset>
</div>
<div id="giftcard-waiting" class="aitcheckout-wait" style="display:none"><img src="<?php echo Mage::getDesign()->getSkinUrl('images/opc-ajax-loader.gif'); ?>" /></div> 
 
<script type="text/javascript">
    aitCheckout.createStep('giftcard',{giftcardUpdateUrl : '<?php echo $this->getUrl('aitcheckout/cart/giftcardPost', array('_secure'=>true)) ?>'}, {
        doCheckErrors : false,
        isLoadWaiting : true,
        isUpdateOnReload : false,
        container: 'checkout-step-giftcard',
        ids: {}
        }
    );
//]]>
</script>