<?php if (Mage::getStoreConfig(Ebizmarts_MailChimp_Model_Config::GENERAL_ACTIVE, $this->_getStoreId()) && Mage::getStoreConfig(Ebizmarts_MailChimp_Model_Config::ENABLE_POPUP, $this->_getStoreId())): ?>


<style type="text/css">

#popupDialog{top: 15% !important;}
.popup_content{
    margin-top: 0;
    margin-bottom: 0;
    background: #FFF;
}
.popupDialog_content .popup_content{
    background: transparent;
}
#popupDialog_content.popup_content{
    height: inherit;
    max-height: 210px;
}

.popup_content .pop-up-text{
    font-size: 14px;
    margin: auto 6%;
}
.popup_message{background: #FFF;}
/*.cancel_button{display: none;}*/
.overlay_popup{ background-color:#000;}
#popupDialog .popup_buttons .ok_button {
    background-image: none;
    text-shadow: none;
    border: none;
    font-family: 'Titillium Web', sans-serif;
    font-weight: 600;
    text-transform: uppercase;
    margin: 10px 0 0;
    padding: 6px 12px;
    color: #ffffff;
    background-color: #c52221;
    border-color: #af1e1d;
    float: right;
    margin-right: 6%;
}
#popupDialog h2{
    font-size: 36px;
    font-weight: 900;
    letter-spacing: .5px;
    line-height: 40px;
    text-transform: uppercase;
    margin-top: 10px;
    color:#008080;
    padding-top: 20px;
}
#popup-form-data input{width: 82%}
#popup-form-data{line-height: 35px;}
.cancel_button {
    position: absolute;
    top: -15%;
    right: 0;
}
@media (max-width:991px){
    #popupDialog .popup_buttons .ok_button{
        margin-right: none;
        margin: 10px auto 20px;
        float: none;
    }
    .popup_message img{width: 100%;}
    #popupDialog_content.popup_content{
        height: auto !important;
    }
    #popupDialog_content.popup_content{
        height: inherit;
        max-height: none;
    }
}
@media (max-width:768px){
    #popupDialog .popup_buttons .ok_button{
        margin: 10px auto 20px;
    }
    #popup-form-data input {
        width: 70%;
    }
    #popupDialog h2{
        font-size: 30px;
        padding-top: 5px;
    }
    .popup_content{
        margin-top: 0;
        margin-bottom: 0;
        background: #FFF;
        height: auto !important;
    }

}
</style>
    <div id="email" style="display:none; overflow:hidden;">
        <div class="row">

            <div class="col-md-6">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('popup_image')->toHtml(); ?> 
            </div>



            <div class="col-md-6">
                <div class="pop-up-text">
                    <h2><?php echo $this->_popupHeading(); ?></h2>

                    <p><?php echo $this->_popupMessage(); ?></p>
                </div>

                <p><span id='email_error_msg' class="email_error" style="display:none">&nbsp;</span></p>

                <div id="popup-form-data">
                    <p>
                        <span class="required"></span>
                        <span class="email_label">Email:</span>
                        <span class="email_input"><input type="text"/></span>
                    </p>

                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript">
        <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        if (navigator.cookieEnabled) {
            <?php if(isset($_COOKIE['email'])):
                if($_COOKIE['email'] != 'none'):
                    Print(json_decode($this->_handleCookie())); ?>
            <?php endif; ?>
            <?php elseif($this->_canCancel()): ?>
            document.observe('keydown', function (evt) {
                if (evt.keyCode == 27) {
                    win.cancelCallback();
                }
            });
            <?php endif; ?>
            document.observe('keydown', function (evt) {
                if (evt.keyCode == 13) {
                    win.okCallback();
                }
            });
            var cookieStored = emailCookieExists();
            if (!cookieStored && $('popupDialog') == undefined) {
				setTimeout(fireEmailPopup, 7000);
				
				function fireEmailPopup(){
					var popupWidth = <?php Print(json_decode(Mage::getStoreConfig(Ebizmarts_MailChimp_Model_Config::POPUP_WIDTH, $this->_getStoreId()))); ?>*window.innerWidth/100;
					var popupHeight = <?php Print(json_decode(Mage::getStoreConfig(Ebizmarts_MailChimp_Model_Config::POPUP_HEIGHT, $this->_getStoreId()))); ?>*window.innerHeight/100;
					var win = Dialog.confirm($('email').innerHTML, {
						className: "popup",
						id: "popupDialog",
						width: popupWidth,

						zIndex: 2001,
						okLabel: '<?php echo $this->__('Confirm') ?>',
						<?php if(!$this->_canCancel()): ?>closeOnEsc: false,
						<?php else: ?>
						cancelLabel: '<?php echo $this->__('Close') ?>',
						onCancel: function (win) {
							<?php if(isset($_COOKIE['counter'])):
							//check cookie counter for customer id and check actual counter
								$counter = $_COOKIE['counter'];
								//if(counter en config == counter en db){
								if(($counter+1) >= Mage::getStoreConfig(Ebizmarts_MailChimp_Model_Config::POPUP_INSIST, Mage::app()->getStore()->getId())): ?>
							Mage.Cookies.clear('counter');
							//document.cookie = 'counter=; expires=Thu, 01 Jan 1970 00:00:01 GMT';
							createCookie('email', 'none', <?php Print(json_encode(Mage::getStoreConfig(Ebizmarts_MailChimp_Model_Config::POPUP_COOKIE_TIME, $this->_getStoreId()))); ?>);
							<?php else: ?>
							createCookie('counter',<?php Print(json_encode((1+$counter))); ?>,<?php Print(json_encode(Mage::getStoreConfig(Ebizmarts_MailChimp_Model_Config::POPUP_COOKIE_TIME, $this->_getStoreId()))); ?>);
	//                        $counter->setCounter(($counter->getCounter()+1));
	//                        $counter->save();
							<?php endif; ?>
							<?php else:
							//create cookie counter in 0
								if (Mage::getStoreConfig(Ebizmarts_MailChimp_Model_Config::POPUP_INSIST, Mage::app()->getStore()->getId()) == 1): ?>
							createCookie('email','none', <?php Print(json_encode(Mage::getStoreConfig(Ebizmarts_MailChimp_Model_Config::POPUP_COOKIE_TIME, $this->_getStoreId()))); ?>);
							<?php else: ?>
							createCookie('counter',1,<?php Print(json_encode(Mage::getStoreConfig(Ebizmarts_MailChimp_Model_Config::POPUP_COOKIE_TIME, $this->_getStoreId()))); ?>);
	//                            $newCounter = Mage::getModel('mailchimp/popup');
	//                            $newCounter->setCounter(1)->save();
	//                        createCookie('counter=' +<?php //Print(json_encode($newCounter->getId())); ?>//, <?php //Print(json_encode(Mage::getStoreConfig(Ebizmarts_MailChimp_Model_Config::POPUP_COOKIE_TIME, $this->_getStoreId()))); ?>//);
							<?php endif; ?>
							<?php endif; ?>
						},
						<?php endif; ?>
						onOk: function (win) {
							var inputFieldEmail = $$('.email_input input[type=text]').first();
							var inputFieldFName = $$('.fname_input input[type=text]').first();
							var inputFieldLName = $$('.lname_input input[type=text]').first();
							var email = inputFieldEmail.value;
							var fname = '';
							var lname = '';
							if(inputFieldFName) {
								fname = inputFieldFName.value;
							}
							if(inputFieldLName) {
								lname = inputFieldLName.value;
							}
							if (validateEmail(email)) {
								createCookie('email',email + '/' + fname + '/' + lname, 365);
								<?php if($this->_modalSubscribe()): ?>
								createCookie('subscribe','true', 365);
								location.reload();
								<?php else: ?>
								win.close();
								<?php endif ?>
							} else {
								$('email_error_msg').innerHTML = '<?php echo $this->__('Not a valid e-mail address') ?>';
								$('email_error_msg').setStyle({color: '#F00'});
								$('email_error_msg').show();
								Windows.focusedWindow.updateHeight();
								new Effect.Shake(Windows.focusedWindow.getId());
							}
						}
					});
					<?php if(!$this->_canCancel()): ?>
					$$('.cancel_button').each(function (element) {
						element.remove();
					});
					<?php else: ?>
					Event.observe(window, 'load', function () {
						$('overlay_modal').observe('click', function () {
							win.close();
							win.cancelCallback();
						});
					});
					<?php endif; ?>
				} // end of fireEmailPopup
			}
        }
        <?php endif; ?>
        function validateEmail(email) {
            var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
            return re.test(email);
        }
        function emailCookieExists() {
            if(Mage.Cookies.get('email')) {
                return true
            }
            else {
                return false
            }
        }
        function createCookie(name, value, expirationInDays) {
            var now = new Date();
            var expire = new Date(now.getTime() + (expirationInDays * 24 * 60) * 60000);//[(1 * 365 * 24 * 60) * 60000] == 1 year  -- (Years * Days * Hours * Minutes) * 60000
            //document.cookie = cookie + '; expires=' + expire + '; path=/';
            Mage.Cookies.expires = expire;
            Mage.Cookies.set(name,value);
        }
    </script>
<?php endif; ?>