<div id="aitgiftwrap-waiting" class="aitcheckout-wait" style="display:none"><img src="<?php echo Mage::getDesign()->getSkinUrl('images/opc-ajax-loader.gif'); ?>" /></div>
<script type="text/javascript">
//<![CDATA[

    aitCheckout.createStep('giftwrap',{
            }, {
                doCheckErrors : false,
                isLoadWaiting : true,
                isUpdateOnReload : false,
                isShowCartInCheckout : <?php echo $this->helper('aitcheckout')->isShowCartInCheckout()?'1':'0'?>,
                container: 'checkout-step-aitgiftwrap'
            }
    );
//]]>
</script>
