<?php
$cfmHelper = Mage::helper('aitcheckout/aitcheckoutfields');
if ($this->helper('aitcheckout')->isCompactDesign()) {
    $compact    = ' compact';
    $name_block = 'aitcheckout/customer_widget_name';
} else {
    $compact    = '';
    $name_block = 'customer/widget_name';
}
?>
<!--     START AITOC CHECKOUT ATTRIBUTES     -->
<?php if (($aFieldList = $cfmHelper->getCustomFieldList('review', 1)) && !$this->isSaveOrderAction()): ?>
    <div id="customreview-aitcheckoutfields-top">
        <fieldset class="buttons-set" style="text-align:left; border-bottom: none;">
            <ul class="form-list<?php echo $compact ?>">
                <?php foreach ($aFieldList as $aField): ?>
                    <?php echo $cfmHelper->getFieldHtml('customreview', $aField); ?>
                <?php endforeach; ?>
            </ul>
        </fieldset>
    </div>
<?php endif; ?>
<!--     FINISH AITOC CHECKOUT ATTRIBUTES     -->
<div class="order-review" id="checkout-review-load">
    <?php echo $this->getChildHtml('items_before'); ?>
    <?php if ($this->helper('aitcheckout')->isShowCartInCheckout() && !$this->isSaveOrderAction()): ?>
        <?php if ($this->helper('aitcheckout')->isCompactDesign()): ?>
            <?php echo $this->getChildHtml('compact_cart') ?>
        <?php else: ?>
            <?php echo $this->getChildHtml('cart') ?>
        <?php endif; ?>
    <?php else: ?>
        <?php echo $this->getChildHtml('info') ?>
    <?php endif; ?>
    <?php echo $this->getChildHtml('items_after'); ?>
</div>
<!--     START AITOC CHECKOUT ATTRIBUTES     -->
<?php if (($aFieldList = $cfmHelper->getCustomFieldList('review', 2)) && !$this->isSaveOrderAction()): ?>
    <div id="customreview-aitcheckoutfields-bottom">
        <fieldset class="buttons-set" style="text-align:left; border-bottom: none;">
            <ul class="form-list<?php echo $compact ?>">
                <?php foreach ($aFieldList as $aField): ?>
                    <?php echo $cfmHelper->getFieldHtml('customreview', $aField); ?>
                <?php endforeach; ?>
            </ul>
        </fieldset>
    </div>
<?php endif; ?>
<!--     FINISH AITOC CHECKOUT ATTRIBUTES     -->
<div id="review-waiting" class="aitcheckout-wait" style="display:none"><img src="<?php echo Mage::getDesign()
        ->getSkinUrl('images/opc-ajax-loader.gif'); ?>"/></div>
<script type="text/javascript">
    //<![CDATA[
    review = new AitMagentoReview('<?php echo $this->getReviewUrl() ?>', '<?php echo $this->getUrl('checkout/onepage/success', array('_secure' => true)) ?>', $('checkout-agreements'));

    //need for save custom checkout fields
    aitCheckout.createStep('customreview', {}, {
            doCheckErrors   : false,
            isLoadWaiting   : false,
            isUpdateOnReload: false,
            container       : 'checkout-step-review',
            ids             : {}
        }
    );

    <?php if ($this->isDisabled()):?>aitCheckout.disableCheckout();
    <?php else: ?>aitCheckout.enableCheckout();<?php endif; ?>

    //]]>
</script>